CakeShopTCC/CakeShopTCC/Controllers/SobreNosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CakeShopTCC.Controllers
{
    public class SobreNosController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CakeShopTCC/CakeShopTCC/Views/Shared/_Layout.cshtml
@using CakeShop.Models
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CakeShop</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.fileupload.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/full-slider.css" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic|Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic|Lato:100,200,300,400,500,600,700,800,900,300italic,400italic&amp;subset=latin,latin-ext" rel="stylesheet" />
    <style type="text/css">
        body {
            font-family: 'Raleway',sans-serif !important;
        }

        h2.meuTexto {
            color: #303030 !important;
            font-family: 'Raleway',sans-serif !important;
            font-size: 32px !important;
            line-height: 40px !important;
            font-style: normal !important;
            font-weight: 700 !important;
            letter-spacing: 3px !important;
            text-transform: uppercase !important;
        }

        h3.meuTexto {
            color: #303030 !important;
            font-family: 'Raleway',sans-serif !important;
            font-size: 20px !important;
            line-height: 34px !important;
            font-style: normal !important;
            font-weight: 300 !important;
            letter-spacing: 0px !important;
            text-transform: none !important;
        }

        .bg-dark {
            background-color: transparent !important;
        }

        .dropdown-menu {
            background-color: transparent !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Content("~/")">CakeShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Content("~/")">
                            Início <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produtos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link active" href="@Url.Action("PaginaBolos", "Produto")">Bolos</a></li>
                            <li><a class="nav-link active" href="@Url.Action("PaginaDoces", "Produto")">Doces</a></li>
                            <li><a class="nav-link active" href="@Url.Action("PaginaSalgados", "Produto")">Salgados</a></li>
                        </ul>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Contato")">Contato</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "SobreNos")">Sobre</a>
                    </li>
                    @if (HttpContext.Current.User.GetType().Name == typeof(Usuario).Name && ((Usuario)User) != null)
                    {
                        <li class="nav-item active dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(((Usuario)User).Nome)<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link active" href="@Url.Action("MinhaConta", "Cliente")">Minha Conta</a></li>
                                <li><a class="nav-link active" href="@Url.Action("MeusPedidos", "Cliente")">Meus Pedidos</a></li>
                                <li><a class="nav-link active" href="@Url.Action("LogOff", "Cliente")">Sair</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Cadastro", "Cliente")">Faça seu cadastro</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer class="py-5 bg-dark" style="background-color: #252525 !important;">
        <div class="container">
            <p class="m-0 text-center text-white">
                CakeShop
            </p>
            <p class="m-0 text-center text-white">
                Endereço: Rua Padre Leonardo Nunes, 180 - Portão
            </p>
            <p class="m-0 text-center text-white">
                Curitiba/PR - CEP 80330-320
            </p>
            <p class="m-0 text-center text-white" style="padding: 10px 0;">
                <a href="@Url.Action("Index", "Login")">
                    Você é uma confeiteira? Clique aqui para acessar a <u>área restrita</u>!
                </a>
            </p>
            <p class="m-0 text-center text-white">Copyright © CakeShop @DateTime.Now.Year</p>
        </div>
    </footer>
    <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/meiomask.min.js"></script>
    <script src="~/Scripts/script.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var scroll_pos = 0;
            $(document).scroll(function () {
                scroll_pos = $(this).scrollTop();
                if (scroll_pos > 657) {
                    $("nav.navbar").attr('style', 'background-color: #252525 !important');
                    $("ul.dropdown-menu").attr('style', 'background-color: #252525 !important');
                } else {
                    $("nav.navbar").attr('style', 'background-color: transparent !important');
                    $("ul.dropdown-menu").attr('style', 'background-color: transparent !important');
                }
            });
            $('html, body').animate({ scrollTop: 0 }, 0);
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CakeShopTCC/CakeShopTCC/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CakeShop</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/jquery.fileupload.css" rel="stylesheet" />
    <style type="text/css">
        body {
            padding-top: 70px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Pedido")">CakeShop</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Pedido")">Pedidos</a></li>
                    <li><a href="@Url.Action("CadastroProduto", "Produto")">Cadastrar Produto</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Listas <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("TabelaClientes", "Usuario")">Lista de Clientes</a></li>
                            <li><a href="@Url.Action("TabelaProdutosBolos", "Usuario")">Lista de Bolos</a></li>
                            <li><a href="@Url.Action("TabelaProdutosDoces", "Usuario")">Lista de Doces</a></li>
                            <li><a href="@Url.Action("TabelaProdutosSalgados", "Usuario")">Lista de Salgados</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("LogOff", "Login")">Sair</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap3.js"></script>
    <script src="~/Scripts/meiomask.min.js"></script>
    <script src="~/Scripts/script.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CakeShopTCC/CakeShopTCC/Views/Shared/_LayoutMenu.cshtml
@using CakeShop.Models
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CakeShop</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.fileupload.css" rel="stylesheet" />
    <link href="~/Content/full-slider.css" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic|Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic|Lato:100,200,300,400,500,600,700,800,900,300italic,400italic&amp;subset=latin,latin-ext" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />
    <style type="text/css">
        body {
            font-family: 'Raleway',sans-serif !important;
            padding-top: 70px;
        }

        h2.meuTexto {
            color: #303030 !important;
            font-family: 'Raleway',sans-serif !important;
            font-size: 32px !important;
            line-height: 40px !important;
            font-style: normal !important;
            font-weight: 700 !important;
            letter-spacing: 3px !important;
            text-transform: uppercase !important;
        }

        h3.meuTexto {
            color: #303030 !important;
            font-family: 'Raleway',sans-serif !important;
            font-size: 20px !important;
            line-height: 34px !important;
            font-style: normal !important;
            font-weight: 300 !important;
            letter-spacing: 0px !important;
            text-transform: none !important;
        }

        .bg-dark {
            background-color: transparent !important;
        }

        .dropdown-menu {
            background-color: transparent !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Content("~/")">CakeShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Content("~/")">
                            Início <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produtos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link active" href="@Url.Action("PaginaBolos", "Produto")">Bolos</a></li>
                            <li><a class="nav-link active" href="@Url.Action("PaginaDoces", "Produto")">Doces</a></li>
                            <li><a class="nav-link active" href="@Url.Action("PaginaSalgados", "Produto")">Salgados</a></li>
                        </ul>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Contato")">Contato</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "SobreNos")">Sobre</a>
                    </li>
                    @if (HttpContext.Current.User.GetType().Name == typeof(Usuario).Name && ((Usuario)User) != null)
                    {
                        <li class="nav-item active dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(((Usuario)User).Nome)<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link active" href="@Url.Action("MinhaConta", "Cliente")">Minha Conta</a></li>
                                <li><a class="nav-link active" href="@Url.Action("MeusPedidos", "Cliente")">Meus Pedidos</a></li>
                                <li><a class="nav-link active" href="@Url.Action("LogOff", "Cliente")">Sair</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Cadastro", "Cliente")">Faça seu cadastro</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer class="py-5 bg-dark" style="background-color: #252525 !important;">
        <div class="container">
            <p class="m-0 text-center text-white">
                CakeShop
            </p>
            <p class="m-0 text-center text-white">
                Endereço: Rua Padre Leonardo Nunes, 180 - Portão
            </p>
            <p class="m-0 text-center text-white">
                Curitiba/PR - CEP 80330-320
            </p>
            <p class="m-0 text-center text-white" style="padding: 10px 0;">
                <a href="@Url.Action("Index", "Login")">
                    Você é uma confeiteira? Clique aqui para acessar a <u>área restrita</u>!
                </a>
            </p>
            <p class="m-0 text-center text-white">Copyright © CakeShop @DateTime.Now.Year</p>
        </div>
    </footer>
    <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/meiomask.min.js"></script>
    <script src="~/Scripts/script.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("nav.navbar").attr('style', 'background-color: #252525 !important');
            $("ul.dropdown-menu").attr('style', 'background-color: #252525 !important');
            $('html, body').animate({ scrollTop: 0 }, 0);
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>